---
title: matrik
jupytext:
  formats: md:myst
  text_representation:
    extension: .md
    format_name: myst
    format_version: '0.13'
    jupytext_version: '1.11.5'
kernelspec:
  display_name: Python 3
  language: python
  name: python3
---

## Matriks

Matriks adalah susunan bilangan berbentuk persegi panjang yang diatur dalam baris dan kolom. Matriks biasanya digunakan dalam berbagai bidang seperti matematika, fisika, dan ilmu komputer untuk merepresentasikan sistem persamaan linear, transformasi geometris, dan operasi lainnya.

### **Operasi Matrik**

### Penjumlahan

Dua matriks dapat dijumlahkan jika memiliki ukuran yang sama. Penjumlahan dilakukan dengan menjumlahkan elemen-elemen yang sesuai.

### Pengurangan

Pengurangan dilakukan dengan cara yang sama seperti penjumlahan, tetapi dengan mengurangi elemen-elemen yang sesuai.

### Perkalian

Perkalian matriks
𝐴
A dan
𝐵
B hanya dapat dilakukan jika jumlah kolom pada
𝐴
A sama dengan jumlah baris pada
𝐵
B.

In [ ]:
import numpy as np

# Definisi matriks
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Penjumlahan Matriks
penjumlahan = A + B

# Pengurangan Matriks
pengurangan = A - B

# Perkalian Matriks
perkalian = np.dot(A, B)  # atau bisa juga menggunakan A @ B

# Menampilkan hasil
print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil Penjumlahan:\n", penjumlahan)
print("Hasil Pengurangan:\n", pengurangan)
print("Hasil Perkalian:\n", perkalian)


Matriks A:
 [[1 2]
 [3 4]]
Matriks B:
 [[5 6]
 [7 8]]
Hasil Penjumlahan:
 [[ 6  8]
 [10 12]]
Hasil Pengurangan:
 [[-4 -4]
 [-4 -4]]
Hasil Perkalian:
 [[19 22]
 [43 50]]
